### Sign In
POST http://localhost:8000/api/login
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "123456"
}

### Transactions

GET http://localhost:8000/api/transactions
Authorization: Bearer token

### Budgets

GET http://localhost:8000/api/budgets
Authorization: Bearer token

### Pots

GET http://localhost:8000/api/pots
Authorization: Bearer token

### Users

GET http://localhost:8000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHRlc3QuY29tIiwicGFzc3dvcmQiOiIxMjM0NTYiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDA3MzI0OTcsImV4cCI6MTc0MDczNjA5N30.XWGyCvmlIfyY0CrIZL8iQuWN52kdmG3Ag2OdTs3kzh4
