### Sign In
POST http://localhost:8000/api/login
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "123456"
}

### Transactions

GET http://localhost:8000/api/transactions
Authorization: Bearer token

### Budgets

GET http://localhost:8000/api/budgets
Authorization: Bearer token

### Pots

GET http://localhost:8000/api/pots
Authorization: Bearer token

### Users

GET http://localhost:8000/api/users
